# Generated by Django 3.2.4 on 2022-08-28 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20220828_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='contact',
            field=models.IntegerField(default=9988776655),
        ),
    ]
