# Generated by Django 3.2.4 on 2022-08-28 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_property_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='property',
            name='email',
        ),
    ]
