# Generated by Django 3.2.4 on 2022-08-28 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20220828_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='contact',
            field=models.IntegerField(default=134567),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='email',
            field=models.EmailField(default=1234, max_length=254),
            preserve_default=False,
        ),
    ]
